src/controllers/FileController.py
import torch
import os
import io
from models.InputFile import InputFile
from models.OutputFile import OutputFile
from flask import Blueprint, render_template, request, redirect, url_for, current_app, send_from_directory
from werkzeug.utils import secure_filename
from helpers.db import insert_input_file, get_input_file, insert_output_file, get_output_file, insert_weights, get_weights
from datetime import datetime
from helpers.Utility import analyze_image, get_file_dimensions, get_file_size, get_file_extension, allowed_file
from flask import session
from time import time
from PIL import Image
from bson.binary import Binary

input_file = Blueprint('input_file', __name__)
output_file = Blueprint('output_file', __name__)

@input_file.route('/upload', methods=['GET', 'POST'])
def insert_inputFile():
    from app import app
    if request.method == 'POST':
        if 'file' not in request.files:
            return redirect(request.url)

        file = request.files['file']

        if file.filename == '':
            return redirect(request.url)

        if not allowed_file(file.filename):
            return redirect(request.url)
        
        filename = secure_filename(file.filename)
        
        # Check if input_file doesn't exist, then insert it. 
        # If it exists and its data is the same, return the existing input_file.
        # If it exists and its data is different, insert the new input_file.
        existing_input_file = get_input_file(filename)
        
        if existing_input_file is None:
            print("===============================")
            print("Uploading " + filename)
            start_time = time()  # Record the start time
            
            if not os.path.exists(app.config['UPLOAD_FOLDER']):
                print("===============================")
                print("Creating " + app.config['UPLOAD_FOLDER'] + " folder")
                os.makedirs(app.config['UPLOAD_FOLDER'])
                
            path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
            
            file.save(path)
            
            elapsed_time = time() - start_time  # Calculate elapsed time
            print("===============================")
            print(f"New input file saved locally at {path} folder in {elapsed_time:.2f} seconds")
            
            start_time = time()  # Reset start time for the next step
            
            dimensions = get_file_dimensions(file)
            size = get_file_size(path)
            extension = get_file_extension(filename)

            elapsed_time = time() - start_time  # Calculate elapsed time
            print("===============================")
            print(f"File dimensions, size, and extension calculated in {elapsed_time:.2f} seconds")
            start_time = time()  # Reset start time for the next step
            
            with open(path, "rb") as image_file:
                input_binary_data = Binary(image_file.read())
                
            loaded_weights_id = session.get('loaded_weights')['_id']
            
            current_date = datetime.now().strftime('%Y-%m-%d %H:%M')
            
            input_file = InputFile(
                filename, 
                dimensions, 
                size, 
                extension, 
                input_binary_data, 
                loaded_weights_id, 
                current_date, 
                current_date, 
                None
            )
            
            session['input_file'] = input_file.__dict__
            
            start_time = time()
            
            insert_input_file()
            
            elapsed_time = time() - start_time
            print("===============================")
            print(f"Inserted new input file to mongodb in {elapsed_time:.2f} seconds")
            print("===============================")
            
            return render_template('index.html', input_file=input_file)
        else:
            print("===============================")
            print("Fetching " + filename)
            start_time = time()
            
            if not os.path.exists(app.config['UPLOAD_FOLDER']):
                print("===============================")
                print("Creating " + app.config['UPLOAD_FOLDER'] + " folder")
                os.makedirs(app.config['UPLOAD_FOLDER'])
            
            input_file = InputFile(
                existing_input_file['name'],
                existing_input_file['dimensions'],
                existing_input_file['size'],
                existing_input_file['extension'],
                existing_input_file['data'],
                existing_input_file['weight_id'],
                existing_input_file['created_at'],
                existing_input_file['updated_at'],
                existing_input_file['deleted_at']
            )
            
            session['input_file'] = input_file.__dict__
            
            stream = io.BytesIO(existing_input_file['data'])
            input_image = Image.open(stream)
            input_image.save(app.config['UPLOAD_FOLDER'] + '/' + existing_input_file['name'])
            
            elapsed_time = time() - start_time  # Calculate elapsed time
            print("===============================")
            print(f"Existing image from mongodb saved to {app.config['UPLOAD_FOLDER']}/{existing_input_file['name']} in {elapsed_time:.2f} seconds")
            print("===============================")
            
            return render_template('index.html', input_file=input_file)

    return render_template('index.html')

@input_file.route('/analyze', methods=['GET', 'POST'])
def insert_outputFile():
    from app import app
    if request.method == 'POST':
        input_file_data = session.get('input_file')

        if input_file_data is None:
            # Redirect to the homepage or show an error message
            return redirect(url_for('input_file.upload'))

        # Access the relevant data from input_file_data dictionary
        filename = input_file_data['name']
        
        # Check if output_file doesn't exist, then insert it.
        # If it exists and its data is the same, return the existing output_file.
        # If it exists and its data is different, insert the new output_file.
        existing_output_file = get_output_file(filename)
        
        if existing_output_file is None:
            print("===============================")
            print("Analyzing " + filename)
            start_time = time()
            
            # Predict the image using the trained YOLO model
            result = analyze_image(filename)
            path = result[0].path
            
            session['output_date'] = path.split('/')[2]
            
            elapsed_time = time() - start_time
            print("\n===============================")
            print(f"Image analyzed in {elapsed_time:.2f} seconds")
            print("New output file saved to " + path + " folder")
            
            start_time = time()
            
            classification = "No Good" if torch.tensor(result[0].boxes.cls).item() > 0 else "Good"
            accuracy = round(torch.tensor(result[0].boxes.conf).item(),2 )
            error_rate = round(1 - accuracy, 2)
            
            elapsed_time = time() - start_time
            print("===============================")
            print(f"Classification, accuracy, and error rate calculated in {elapsed_time:.2f} seconds")
            
            with open(path, "rb") as image_file:
                input_binary_data = Binary(image_file.read())
            
            input_id = get_input_file(filename)['_id']
            
            current_date = datetime.now().strftime('%Y-%m-%d %H:%M')
            
            output_file = OutputFile(
                filename,
                classification,
                accuracy,
                error_rate,
                input_binary_data,
                input_id,
                current_date,
                current_date,
                None
            )
            
            session['output_file'] = output_file.__dict__
            
            start_time = time()
            
            insert_output_file()
            
            elapsed_time = time() - start_time
            print("===============================")
            print(f"Inserted new output file to mongodb in {elapsed_time:.2f} seconds")
            print("===============================")
            
            return render_template('index.html', input_file=input_file_data, output_file=output_file)
        else:
            print("===============================")
            print("Fetching " + existing_output_file['name'])
            start_time = time()
            
            older_date = existing_output_file['created_at'].replace(':', '-').replace(' ', '_')

            if not os.path.exists(app.config['PREDICTIONS_FOLDER'] + "/" +  older_date):
                print("===============================")
                print("Creating " + app.config['PREDICTIONS_FOLDER'] + " folder")
                os.makedirs(app.config['PREDICTIONS_FOLDER'] + "/" +  older_date)
                
            older_path = app.config['PREDICTIONS_FOLDER'] + "/" + older_date + '/' + existing_output_file['name']
            
            session['output_date'] = older_date
            
            output_file = OutputFile(
                existing_output_file['name'],
                existing_output_file['classification'],
                existing_output_file['accuracy'],
                existing_output_file['error_rate'],
                existing_output_file['data'],
                existing_output_file['input_id'],
                existing_output_file['created_at'],
                existing_output_file['updated_at'],
                existing_output_file['deleted_at']
            )
            

src/templates/archived.html
<!DOCTYPE html>
<html>
<head>
  <title>Archived</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/archived.css') }}">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
</head>
<body>
  <div class="sidebar">   
    {% include 'sidebar.html' %}
  </div>
  <div class="p-4 sm:ml-64">
    <div class="p-4">
      <div class="flex items-start justify-left h-full mb-4 rounded bg-gray-100 p-6 flex-col">       
        <h1 class="text-3xl font-bold mb-1">IMAGES</h1>
        <h2>Archived Images</h2> 
      </div>
    </div>
  </div>
</body>
</html>

src/templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/dashboard.css') }}">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
</head>
<body>
  <div class="sidebar">   
    {% include 'sidebar.html' %}
  </div>
  <div class="p-4 sm:ml-64">
    <div class="p-4">
      <div class="flex items-start justify-left h-full mb-4 rounded bg-gray-100 p-6 flex-col">       
        <h1 class="text-3xl font-bold mb-1">OVERVIEW</h1>
      </div>
    </div>
  </div>
</body>
</html> 

src/templates/helpsupport.html
<!DOCTYPE html>
<html>
<head>
  <title>Help and Support</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/helpsupport.css') }}">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
</head>
<body>
  <div class="sidebar">   
    {% include 'sidebar.html' %}
  </div>
  <div class="p-4 sm:ml-64">
    <div class="p-4">
      <div class="flex items-start justify-left h-full mb-4 rounded bg-gray-100 p-6 flex-col">       
        <h1 class="text-3xl font-bold mb-4">Help Topics</h1>
        <div class="card-group">
          <div class="card">
            <img src="{{ url_for('static', filename='images/img1.png') }}" class="icon" width="100px" height="100px" alt="Watch Video Icon">
            <h2>Watch Video</h2>
            <p>Find helpful video tutorials to guide you through the process.</p>
          </div>
          <div class="card">
            <img src="{{ url_for('static', filename='images/img2.png') }}" class="icon1" width="80px" height="80px" alt="Get Started Icon">
            <h2>Getting Started</h2>
            <p>Learn how to get started with our product or service.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

src/templates/history.html
<!DOCTYPE html>
<html>
<head>
  <title>History</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/history.css') }}">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
</head>
<body>
  <div class="sidebar">   
    {% include 'sidebar.html' %}
  </div>
  <div class="p-4 sm:ml-64">
    <div class="p-4">
      <div class="flex items-start justify-left h-full mb-4 rounded bg-gray-100 p-6 flex-col card">       
        <h1 class="text-3xl font-bold mb-1">IMAGES</h1>
        <div class="sub">
          <h2>All Images History</h2>
          <button>Clear History</button>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

src/templates/index.html
<!DOCTYPE html>
<html>

<head>
  <title>Image Upload</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
</head>

<body>
  {% include 'sidebar.html' %}
  <div class="p-4 sm:ml-64">
    <div class="p-4">
      <div class="flex flex-col gap-x-1 items-left justify-between mb-4 h-48 rounded bg-gray-100 p-6">
        <h1 class="text-5xl font-bold">LSC Quality Inspector</h1>
        <form method="POST" enctype="multipart/form-data" action="{{ url_for('input_file.insert_inputFile') }}"
          class="flex justify-between">
          <input type="file" name="file" accept=".txt, .pdf, .png, .jpg, .jpeg, .gif">
          <input type="submit" value="Upload"
            class="w-24 py-2 text-white bg-green-400 cursor-pointer hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm">
        </form>
      </div>

      <div class="flex flex-col items-start justify-between h-72 mb-4 rounded bg-gray-100 p-6 relative">
        <h1 class="text-xl font-bold">Uploaded File</h1>
        {% if input_file %}
        <div class="flex items-start justify-left">
          <img src="{{ url_for('input_file.get_file', filename=input_file.name) }}" alt="Uploaded Image"
            class="h-full w-80 mr-6">

          <div class="grid grid-cols-2 gap-x-4">
            <p class="font-bold">Filename: </p>
            <p>{{ input_file.name }}</p>
            <p class="font-bold">Dimensions: </p>
            <p>{{ input_file.dimensions }}</p>
            <p class="font-bold">Size: </p>
            <p>{{ input_file.size }}</p>
            <p class="font-bold">Extension: </p>
            <p>{{ input_file.extension }}</p>
          </div>
          <form method="POST" enctype="multipart/form-data" action="{{ url_for('input_file.insert_outputFile') }}"
            class="flex justify-between absolute mr-6 right-0">
            <input type="submit" value="Analyze"
              class="w-24 py-2.5 text-white bg-green-400 cursor-pointer hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm">
          </form>
        </div>
        {% else %}
        <div role="status" class="space-y-8 animate-pulse md:space-y-0 md:space-x-8 md:flex md:items-center">
          <div class="flex items-center justify-center w-full h-48 bg-gray-300 rounded sm:w-96 dark:bg-gray-700">
              <svg class="w-10 h-10 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
                  <path d="M18 0H2a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2Zm-5.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm4.376 10.481A1 1 0 0 1 16 15H4a1 1 0 0 1-.895-1.447l3.5-7A1 1 0 0 1 7.468 6a.965.965 0 0 1 .9.5l2.775 4.757 1.546-1.887a1 1 0 0 1 1.618.1l2.541 4a1 1 0 0 1 .028 1.011Z"/>
              </svg>
          </div>
          <div class="w-full">
              <div class="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-48 mb-4"></div>
              <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[480px] mb-2.5"></div>
              <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 mb-2.5"></div>
              <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[440px] mb-2.5"></div>
              <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[460px] mb-2.5"></div>
              <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px]"></div>
          </div>
          <span class="sr-only">Loading...</span>
        </div>
        {% endif %}
      </div>

      <div class="flex flex-col items-start justify-between h-72 mb-4 rounded bg-gray-100 p-6">
        <h1  class="text-xl font-bold">Output File</h1>
        {% if output_file %}
        <div class="flex">
          <img src="{{ url_for('output_file.get_file', filename=output_file.name, date=session['output_date']) }}" alt="Predicted Image"
          class="h-full w-80 mr-6">     
          <div class="flex gap-x-4 w-min">
            <div>
              <p class="font-bold">Classification: </p>
              <p class="font-bold">Accuracy: </p>
              <p class="font-bold">Error Rate: </p>
              <p class="font-bold">Path: </p>
            </div>
            <div>
              <p class="{{ 'text-green-500' if output_file.classification == 'Good' else 'text-red-500' }}">{{ output_file.classification }}</p>
              <p>{{ output_file.accuracy }}</p>
              <p>{{ output_file.error_rate }}</p>
              <p>src{{ url_for('output_file.get_file', filename=output_file.name, date=session['output_date']) }}</p>
            </div>
          </div>
        </div>
        {% else %}
        <div role="status" class="space-y-8 animate-pulse md:space-y-0 md:space-x-8 md:flex md:items-center">
          <div class="flex items-center justify-center w-full h-48 bg-gray-300 rounded sm:w-96 dark:bg-gray-700">
              <svg class="w-10 h-10 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
                  <path d="M18 0H2a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2Zm-5.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm4.376 10.481A1 1 0 0 1 16 15H4a1 1 0 0 1-.895-1.447l3.5-7A1 1 0 0 1 7.468 6a.965.965 0 0 1 .9.5l2.775 4.757 1.546-1.887a1 1 0 0 1 1.618.1l2.541 4a1 1 0 0 1 .028 1.011Z"/>
              </svg>
          </div>
          <div class="w-full">
              <div class="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-48 mb-4"></div>
              <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[480px] mb-2.5"></div>
              <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 mb-2.5"></div>
              <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[440px] mb-2.5"></div>
              <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[460px] mb-2.5"></div>
              <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px]"></div>
          </div>
          <span class="sr-only">Loading...</span>
        </div>
        {% endif %}
      </div>
      
    </div>
  </div>
</body>

</html>

src/templates/sidebar.html
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

<button data-drawer-target="default-sidebar" data-drawer-toggle="default-sidebar" aria-controls="default-sidebar"
    type="button"
    class="inline-flex items-center p-2 mt-2 ml-3 text-sm text-white rounded-lg sm:hidden hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-gray-200">
    <span class="sr-only">Open sidebar</span>
    <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
      <path clip-rule="evenodd" fill-rule="evenodd"
        d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z">
      </path>
    </svg>
  </button>

  <aside id="default-sidebar"
    class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
    aria-label="Sidebar">
    <div class="h-full px-3 py-4 overflow-y-auto bg-green-400">
      <ul class="space-y-2 font-medium">
        <li class="sidebar-item">
          <a href="/dashboard" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-blue-200 group">
            <span class="material-symbols-outlined" style="color: white;">
              dashboard
              </span>
            <span class="ml-3 text-white group-hover:text-gray-900 help-support-text">Dashboard</span>
          </a>
        </li>
        <li class="sidebar-item">
          <a href="/" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-blue-200 group">
            <span class="material-symbols-outlined" style="color: white;">
              home
              </span>
            <span class="flex-1 ml-3 whitespace-nowrap text-white group-hover:text-gray-900 help-support-text">Home</span>
          </a>
        </li>               
        <li class="sidebar-item">
          <a href="/history" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-blue-200 group">
            <span class="material-symbols-outlined" style="color: white;">
              history
              </span>
            <span class="flex-1 ml-3 whitespace-nowrap text-white group-hover:text-gray-900 help-support-text">History</span>
          </a>
        </li>
        <li class="sidebar-item">
          <a href="/archived" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-blue-200 group">
            <span class="material-symbols-outlined" style="color: white;">
              archive
              </span>
            <span class="flex-1 ml-3 whitespace-nowrap text-white group-hover:text-gray-900 help-support-text">Archived</span>
          </a>
        </li>
        <li class="sidebar-item">
          <a href="/help-and-support" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-blue-200 group ">
            <span class="material-symbols-outlined" style="color: white;">
              help
              </span>
            <span class="flex-1 ml-3 whitespace-nowrap text-white group-hover:text-gray-900 help-support-text">Help and Support</span>
          </a>
        </li>
      </ul>
    </div>
  </aside>
  <style>
    /* Add this CSS to set text color to black when active */
    .sidebar-item.active .help-support-text {
      color: black;
    }
  </style>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const sidebarItems = document.querySelectorAll('.sidebar-item');

      function setActiveItem() {
        const currentURL = window.location.pathname;
        sidebarItems.forEach(item => {
          const link = item.querySelector('a');
          const svgIcon = item.querySelector('.svg-icon');
          if (link.getAttribute('href') === currentURL) {
            item.classList.add('rounded-lg', 'bg-blue-200', 'text-gray-900', 'active');
            svgIcon.setAttribute('fill', 'black');
          } else {
            item.classList.remove('rounded-lg', 'bg-blue-200', 'text-gray-900', 'active');
            svgIcon.setAttribute('fill', 'currentColor');
          }
        });
      }

      sidebarItems.forEach(item => {
        item.addEventListener('click', () => {
          sidebarItems.forEach(item => {
            item.classList.remove('rounded-lg', 'bg-blue-200', 'text-gray-900', 'active');
            const svgIcon = item.querySelector('.svg-icon');
            svgIcon.setAttribute('fill', 'currentColor');
          });
          item.classList.add('rounded-lg', 'bg-blue-200', 'text-gray-900', 'active');
          const svgIcon = item.querySelector('.svg-icon');
          svgIcon.setAttribute('fill', 'black');
          setActiveItem();
        });
      });

      // Set active item when the page is loaded initially
      setActiveItem();
    });
  </script>